name: schema7
recipe: drupal7
config:
  webroot: docroot
  xdebug: true
  via: apache
  php: '5.5'
env_file:
  - .env

services:
  appserver:
    webroot: docroot
    type: php
  database:
    type: mariadb

events:
  post-start:
    - bash /app/scripts/lando/post-start.sh
  post-db-import:
    - appserver: /usr/local/bin/drush updb --root=/app/docroot -y
    - appserver: /usr/local/bin/drush cc all -y --root=/app/docroot
    - appserver: /usr/local/bin/drush upwd admin --password=password --root=/app/docroot
    - appserver: echo "Log in with credentials admin/password"
  pre-test:
    - appserver: /usr/local/bin/drush --root=/app/docroot --uri=http://appserver en simpletest -y  

tooling:
  test:
    service: appserver
    description: "Run tests: lando run-tests"
    cmd: 'php /app/docroot/scripts/run-tests.sh --url http://appserver --php /usr/local/bin/php --verbose --color'
  drush:
    service: appserver
    cmd: 'drush --root=/app/docroot'   