name: schema7
recipe: drupal7
config:
  webroot: docroot
  xdebug: true
  via: apache
  php: '5.5'

services:
  appserver:
    run:
      - "mkdir -p files/private/db"
  database:
    type: mariadb

events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush --root=/app/docroot --uri=http://appserver updb -y
    - appserver: cd $LANDO_WEBROOT && drush --root=/app/docroot --uri=http://appserver cc all -y
  pre-test:
    - appserver: cd $LANDO_WEBROOT && drush --root=/app/docroot --uri=http://appserver en simpletest -y  

tooling:
  test:
    service: appserver
    description: "Run tests: lando run-tests"
    cmd: 'php /app/docroot/scripts/run-tests.sh --url http://appserver --php /usr/local/bin/php --verbose --color'
  drush:
    service: appserver
    cmd: 'drush --root=/app/docroot'   